version: '3'
services:
    postgres:
        image: postgres:15.0-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_DB=task_manager
            - POSTGRES_USER=tm_admin
            - POSTGRES_PASSWORD=admin
            - PGDATA=/var/lib/postgresql/data/
        volumes:
            - ./init_db.sql:/docker-entrypoint-initdb.d/init_mqtt_log.sql
            - ./pg_data_1:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
             postgres:
                aliases:
                    - postgres-test

    pgadmin:
        image: dpage/pgadmin4:7.2
        environment:
            PGADMIN_DEFAULT_EMAIL: "flages1325@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "asdfasdfsdf"
            PGADMIN_CONFIG_SERVER_MODE: "False"
        ports:
            - "5050:80"
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 1G
        networks:
            - postgres
networks:
    postgres:
volumes:
    db: